### ISSUE TITLE
PyTorch version used for demo/training

### ISSUE THREAD

**Issue by jsigee87** [castorini/honk#56]
On a fresh installation the PyTorch website gives the newest version to download. This causes an error when trying to launch the demo. I am on Ubuntu 16.04, Python 3.5.2, without CUDA. The config.json shows no_cuda as false. When I run `python  .` in the demo instructions I get the following error:

```
 python .
./utils/model.py:143: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  x = Variable(torch.zeros(1, 1, height, width), volatile=True)
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 21, in <module>
    main()
  File "./__main__.py", line 18, in main
    server.start(config)
  File "./server.py", line 144, in start
    lbl_service = load_service(config)
  File "./server.py", line 128, in load_service
    lbl_service = TorchLabelService(model_path, labels=commands, no_cuda=config["model_options"]["no_cuda"])
  File "./service.py", line 78, in __init__
    self.reload()
  File "./service.py", line 85, in reload
    self.model.cuda()
  File "/home/johnsigmon/programming/ml-sandbox/reactions/reaction-009-AVR/honk/.env/lib/python3.5/site-packages/torch/nn/modules/module.py", line 258, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/johnsigmon/programming/ml-sandbox/reactions/reaction-009-AVR/honk/.env/lib/python3.5/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home/johnsigmon/programming/ml-sandbox/reactions/reaction-009-AVR/honk/.env/lib/python3.5/site-packages/torch/nn/modules/module.py", line 191, in _apply
    param.data = fn(param.data)
  File "/home/johnsigmon/programming/ml-sandbox/reactions/reaction-009-AVR/honk/.env/lib/python3.5/site-packages/torch/nn/modules/module.py", line 258, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: Cannot initialize CUDA without ATen_cuda library. PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this error has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason.  The CUDA library MUST be loaded, EVEN IF you don't directly use any symbols from the CUDA library! One common culprit is a lack of -Wl,--no-as-needed in your link arguments; many dynamic linkers will delete dynamic library dependencies if you don't depend on any of their symbols.  You can check if this has occurred by using ldd on your binary to see if there is a dependency on *_cuda.so library.
```

If you have the PyTorch version used for the demo that seems the easiest way for me to get past this. Let me know if you have other suggestions though. Thanks!

**Comment by daemon** [comment]
Does setting `no_cuda` as true fix that issue? If not, then it's probably a bug.
