### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for SpeechResModel

### ISSUE THREAD

**Issue by mausamsion** [castorini/honk#88]
Hey guys,
I am trying to do the evaluation using for speech_commands dataset (a reduced one where I chose only some keywords).
The data directory looks like this:
```
.
├── _unknown_
│   ├── dog_2c6d3924_nohash_2.wav.wav
│   ├── dog_43fc47a7_nohash_0.wav.wav
│   ├── dog_4c6167ca_nohash_1.wav.wav
├── down
│   ├── 022cd682_nohash_0.wav
│   ├── 0c40e715_nohash_0.wav
│   ├── 0c540988_nohash_0.wav
├── go
│   ├── 022cd682_nohash_0.wav
│   ├── 022cd682_nohash_1.wav
│   ├── 0487ba9b_nohash_0.wav
├── left
│   ├── 022cd682_nohash_0.wav
│   ├── 022cd682_nohash_1.wav
│   ├── 03401e93_nohash_0.wav
└── no
    ├── 03401e93_nohash_0.wav
    ├── 03401e93_nohash_1.wav
    ├── 03401e93_nohash_2.wav
```
The command used for evaluation is:
```
python -m utils.train \
    --gpu_no 3 \
    --data_folder /Google_Speech_Commands/chosen \
    --type eval \
    --wanted_words _unknown_ down go left no \
    --model res8 \
    --input_file /root/honk/model/res8.pt
```
Here is the error it thows:
```
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/honk/utils/train.py", line 188, in <module>
    main()
  File "/root/honk/utils/train.py", line 185, in main
    evaluate(config)
  File "/root/honk/utils/train.py", line 66, in evaluate
    model.load(config["input_file"])
  File "/root/honk/utils/model.py", line 80, in load
    self.load_state_dict(torch.load(filename, map_location=lambda storage, loc: storage))
  File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SpeechResModel:
	Unexpected key(s) in state_dict: "scale1.scale", "scale3.scale", "scale5.scale".
```
Can anyone help on this please?

**Comment by daemon** [comment]
Sorry, we screwed up the model file for that. You can either revert to an earlier version of honk-models or wait for us to revert.

**Comment by ljj7975** [comment]
@ultimateMJ 
It looks to me that the issue has been resolved.
Closing for now, please reopen if not
